# 1. Create a 3x3x3 array with random values

In [71]:
import numpy as np

s= np.random.random((3, 3, 3))

print(s)

[[[0.14058193 0.35076493 0.67771201]
  [0.25983064 0.92812015 0.54125782]
  [0.61307017 0.97250419 0.45237555]]

 [[0.68392337 0.96199296 0.59475172]
  [0.11584762 0.28102903 0.09085544]
  [0.61826673 0.89737965 0.37843533]]

 [[0.23604461 0.7891695  0.89475608]
  [0.8411527  0.09487431 0.7624529 ]
  [0.49657267 0.4033743  0.01199618]]]


# 2. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [8]:
import numpy as np

s= np.zeros((5, 5))
print(s)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [10]:
s[1][0] = 1
s[2][1] = 2
s[3][2] = 3
s[4][3] = 4

In [11]:
print(s)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


# 3. Create a 8x8 matrix and fill it with a checkerboard pattern

In [13]:
import numpy as np

s= np.zeros((8, 8), dtype=int)
print(s)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


In [14]:
s[1::2, ::2] = 1
s[::2, 1::2] = 1

print(s)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [18]:
import numpy as np

x= np.random.rand(5, 5)

mean = np.mean(x)
std_dev = np.std(x)

norm_mat = (x - mean) / std_dev

print("Random Matrix:")
print(x)
print()
print("Normalized Matrix:")
print(norm_mat)

Random Matrix:
[[0.41477563 0.50400701 0.29287375 0.31209913 0.34356844]
 [0.01844561 0.9535536  0.73491928 0.58697487 0.98047088]
 [0.71141609 0.68153731 0.68420382 0.84093897 0.19912941]
 [0.16172084 0.30234677 0.17973379 0.94987179 0.65211879]
 [0.41445542 0.786564   0.49578495 0.96105564 0.60160958]]

Normalized Matrix:
[[-0.49392935 -0.16935798 -0.93733684 -0.8674062  -0.75293933]
 [-1.93554533  1.46582868  0.67056532  0.13243042  1.56373792]
 [ 0.58507452  0.47639304  0.48609225  1.05620272 -1.27832372]
 [-1.41439415 -0.90287956 -1.3488736   1.45243639  0.36938577]
 [-0.49509408  0.85841852 -0.19926499  1.4931167   0.18566289]]


# 5. How to find common values between two arrays?

In [25]:
import numpy as np

arr1=np.array([1,3,5,7,9,11,13])
arr2=np.array([2,4,6,1,8,11,10,13])

x=np.intersect1d(arr1,arr2)

print("Array1: ",arr1)
print("Array2: ",arr2)
print("The common vales in both the array are: ",x)

Array1:  [ 1  3  5  7  9 11 13]
Array2:  [ 2  4  6  1  8 11 10 13]
The common vales in both the array are:  [ 1 11 13]


# 6. How to get the dates of yesterday, today and tomorrow?


In [23]:
import numpy as np
from datetime import datetime, timedelta

today = datetime.now().date()

date_range = np.array([today - timedelta(days=1), today, today + timedelta(days=1)], dtype='datetime64[D]')

print("Yesterday:", date_range[0])
print("Today:", date_range[1])
print("Tomorrow: ",date_range[2])

Yesterday: 2023-09-20
Today: 2023-09-21
Tomorrow:  2023-09-22


# 7. Consider two random array A and B, check if they are equal

In [32]:
import numpy as np

x=np.random.random((4,4))
y=np.random.random((4,4))
print(x)
print()
print(y)

s=np.array_equal(x,y)
if s:
    print("Both x and y arrays are equal")
    
else:
    print("Not Equal")


[[0.13696947 0.97072153 0.34274028 0.36415533]
 [0.60644836 0.93559931 0.14721494 0.14060404]
 [0.99809832 0.71986436 0.92396758 0.45585351]
 [0.46608491 0.48337887 0.48636098 0.42271169]]

[[0.22670066 0.01046564 0.78770002 0.43339642]
 [0.42255181 0.61772604 0.23864892 0.94863114]
 [0.02027848 0.68364765 0.53885713 0.09969158]
 [0.38602139 0.95973489 0.02955921 0.73151636]]
Not Equal



# 8. Create random vector of size 10 and replace the maximum value by 0

In [37]:
import numpy as np

s= np.random.random((10))

max_v = np.argmax(s)

s[max_v] = 0


print("Random Vector: ",x)
print()
print("Random Vector with Maximum Value Replaced:", s)

Random Vector:  [[0.13696947 0.97072153 0.34274028 0.36415533]
 [0.60644836 0.93559931 0.14721494 0.14060404]
 [0.99809832 0.71986436 0.92396758 0.45585351]
 [0.46608491 0.48337887 0.48636098 0.42271169]]

Random Vector with Maximum Value Replaced: [0.03383359 0.55793303 0.19772012 0.16903038 0.11027515 0.11286949
 0.10067504 0.20546676 0.         0.07270764]


# 9. How to print all the values of an array?

In [38]:
import numpy as np

x= np.array([1,2,3,4,5,6,7,8,9])
print(x)

[1 2 3 4 5 6 7 8 9]


# 10. Subtract the mean of each row of a matrix

In [45]:
import numpy as np


x= np.array([[1, 2, 3],
            [4, 5, 6],
            [7, 8, 9]])


row= np.mean(matrix, axis=1)

matrix_m = matrix - row[:, np.newaxis]

print("Original Matrix: ")
print(matrix)
print()
print("Matrix with Mean of Each Row Subtracted:")
print(matrix_m)

Original Matrix: 
[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]

Matrix with Mean of Each Row Subtracted:
[[ 0.   0.   0.   0.   0. ]
 [ 0.8 -0.2 -0.2 -0.2 -0.2]
 [-0.4  1.6 -0.4 -0.4 -0.4]
 [-0.6 -0.6  2.4 -0.6 -0.6]
 [-0.8 -0.8 -0.8  3.2 -0.8]]


# 11. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?


In [87]:
import numpy as np
x=np.array([1,2,3,4,5])
y=np.array([1,2,3,3,4])

o=np.zeros_like(x)
for i in y:
    o[i] +=1
    
print("Given Vector is: \n",x)
print("Final vector with 1 added is: \n",o)


Given Vector is: 
 [1 2 3 4 5]
Final vector with 1 added is: 
 [0 1 1 2 1]


# 12. How to get the diagonal of a dot product?

In [52]:
import numpy as np

x= np.array([[1,3,7],[9,11,13],[15,17,19]])

y= np.array([[2,4,6],[8,10,12],[14,16,18]])

dot_product= np.dot(x,y)
diagonal_d= np.diag(dot_product)

print("Matrix A:\n", x)
print()
print("Matrix B:\n", y)
print()
print("Dot Product:\n",dot_product)
print()
print("Diagonal of Dot Product:\n",diagonal_d)

Matrix A:
 [[ 1  3  7]
 [ 9 11 13]
 [15 17 19]]

Matrix B:
 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]

Dot Product:
 [[124 146 168]
 [288 354 420]
 [432 534 636]]

Diagonal of Dot Product:
 [124 354 636]


# 13. How to find the most frequent value in an array?

In [63]:
import numpy as np

x= np.random.randint(0,10,50)

unique_values, counts = np.unique(x, return_counts=True)
most_frequent_value = unique_values[np.argmax(counts)]

print("Your array:\n",x)
print("Most Frequent Value:", most_frequent_value)

Your array:
 [3 1 7 2 9 6 9 3 5 1 5 8 1 2 4 5 6 6 8 8 2 1 3 8 5 4 9 6 5 5 3 1 0 2 6 3 6
 5 4 4 3 0 4 5 2 1 8 3 0 3]
Most Frequent Value: 3


# 14. How to get the n largest values of an array

In [70]:
import numpy as np

x= np.array([1,8,9,7,5,6,4,2,3,8,10])
n = 3
sorted_indices = np.argsort(x)
print(sorted_indices)

n_largest_values = x[sorted_indices[-n:]]

print("Array:",x)
print(f"{n} Largest Values:", n_largest_values)

[ 0  7  8  6  4  5  3  1  9  2 10]
Array: [ 1  8  9  7  5  6  4  2  3  8 10]
3 Largest Values: [ 8  9 10]


# 15. How to create a record array from a regular array?

In [75]:
import numpy as np

x= np.array([("Sravan", 22), ("Pavan", 11), ("Govind", 33)],dtype=[("name", "U10"), ("age", int)])


y= np.rec.fromarrays(x.T)

print("Regular Array:",x)
print("Record Array:",y)

Regular Array: [('Sravan', 22) ('Pavan', 11) ('Govind', 33)]
Record Array: (('Sravan', 22), ('Pavan', 11), ('Govind', 33))


# 16. How to swap two rows of an array? 

In [80]:
import numpy as np

array = np.array([[1,2,3],[4,5,6],[7,8,9]])

row1_index = 0 
row2_index = 1


array[row1_index], array[row2_index] = array[row2_index].copy(), array[row1_index].copy()

print("Original Array: \n",array)

Original Array: 
 [[4 5 6]
 [1 2 3]
 [7 8 9]]


# 17. Write python code to reshape to the next dimension of numpy array?

In [83]:
x=np.array([[23,34,121],[23,22,67],[686,434,123]])
reshaped_x = x.reshape(x.shape[0], x.shape[1], 1)

print("Original Array:")
print(x)

print("\nReshaped Array:")
print(reshaped_x)

Original Array:
[[ 23  34 121]
 [ 23  22  67]
 [686 434 123]]

Reshaped Array:
[[[ 23]
  [ 34]
  [121]]

 [[ 23]
  [ 22]
  [ 67]]

 [[686]
  [434]
  [123]]]
